// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef cool_la_gui_h
#define cool_la_gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Value_Slider.H>
extern Fl_Value_Slider *HRot;
extern Fl_Value_Slider *VRot;
extern Fl_Value_Slider *ZRot;
extern Fl_Value_Slider *Dots;
#include "cool-la.h"
extern Cool *CoolBox;
Fl_Double_Window* make_window();
#endif
